import type { Logger } from "@caporal/core";
import { chmodSync, existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { REPOSITORIES } from "../../lib/repositories";

interface InitScriptOptions {
  output: string;
  ssh: boolean;
  workspace: boolean;
  connectionsFromEnv: boolean;
}

interface WorkspaceFolder {
  name?: string;
  path: string;
}

interface SqlConnection {
  ssh: string;
  previewLimit: number;
  server: string;
  port: number;
  driver: string;
  name: string;
  group: string;
  database: string;
  password: string;
  username: string;
}

function parseEnvFile(envPath: string): Record<string, string> {
  const content = readFileSync(envPath, "utf-8");
  const out: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (value.startsWith('"') && value.endsWith('"')) {
      out[key] = value.slice(1, -1).replace(/\\"/g, '"');
    } else if (value.startsWith("'") && value.endsWith("'")) {
      out[key] = value.slice(1, -1).replace(/\\'/g, "'");
    } else {
      out[key] = value;
    }
  }
  return out;
}

function connectionFromSupabaseEnv(env: Record<string, string>): SqlConnection | null {
  const connectionString = env.SUPABASE_CONNECTION_STRING;
  if (!connectionString?.startsWith("postgresql://")) return null;
  try {
    const u = new URL(connectionString);
    const name =
      env.SUPABASE_PROJECT_REF ?? u.hostname?.replace(/\./g, "-") ?? "supabase";
    return {
      ssh: "Disabled",
      previewLimit: 50,
      server: u.hostname ?? "",
      port: parseInt(u.port || "5432", 10),
      driver: "PostgreSQL",
      name,
      group: "BLT",
      database: u.pathname?.slice(1) || "postgres",
      password: decodeURIComponent(u.password ?? ""),
      username: decodeURIComponent(u.username ?? ""),
    };
  } catch {
    return null;
  }
}

/**
 * Generate a shell script that clones or pulls all BLT projects into the current directory
 */
export async function generateInitScript(
  options: InitScriptOptions,
  logger: Logger,
): Promise<void> {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# BLT project init script - clones or pulls all projects into the current directory",
    "# Generated by: blt init",
    "",
    'set -e',
    "",
    "cd \"$(dirname \"$0\")\"",
    "",
  ];

  for (const repo of REPOSITORIES) {
    const url = options.ssh ? repo.sshUrl : repo.url;
    lines.push(`# ${repo.description || repo.name}`);
    lines.push(`if [ -d "${repo.name}" ]; then`);
    lines.push(`  echo "Pulling ${repo.name}..."`);
    lines.push(`  (cd ${repo.name} && git pull)`);
    lines.push(`else`);
    lines.push(`  echo "Cloning ${repo.name}..."`);
    lines.push(`  git clone ${url} ${repo.name}`);
    lines.push(`fi`);
    lines.push("");
  }

  lines.push("echo \"Done! All projects are up to date.\"");

  const script = lines.join("\n");

  try {
    await Bun.write(options.output, script);

    // Make executable on Unix
    try {
      chmodSync(options.output, 0o755);
    } catch {
      // chmod may fail on Windows, ignore
    }

    logger.info(`Created init script: ${options.output}`);

    if (options.workspace || options.connectionsFromEnv) {
      const baseDir = resolve(dirname(options.output));
      const workspacePath = join(baseDir, "blt.code-workspace");
      const workspaceContent: {
        folders?: WorkspaceFolder[];
        settings?: { "sqltools.connections"?: SqlConnection[] };
      } = {};

      if (options.workspace) {
        workspaceContent.folders = REPOSITORIES.map((repo) => ({
          name: repo.name,
          path: repo.name,
        }));
      }

      if (options.connectionsFromEnv) {
        const envPath = join(baseDir, ".env");
        if (existsSync(envPath)) {
          const env = parseEnvFile(envPath);
          const connection = connectionFromSupabaseEnv(env);
          if (connection) {
            workspaceContent.settings = {
              "sqltools.connections": [connection],
            };
          }
        }
      }

      // Ensure we have at least folders so the file is valid
      if (!workspaceContent.folders) {
        workspaceContent.folders = [];
      }

      await Bun.write(
        workspacePath,
        JSON.stringify(workspaceContent, null, "\t") + "\n",
      );
      logger.info(`Created workspace: ${workspacePath}`);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to write script: ${message}`);
    process.exit(1);
  }
}
